### ISSUE TITLE
Update Thumbor cache clear functionality to clear both destinations

### ISSUE THREAD

**Issue by phg49389** [betheluniversity/cache-clear#3]
Tinker's code only clears the "original" (raw download by Thumbor, stored before resizing) version from the FILE_STORAGE location (thumbor_storage/original_images), but not from the RESULT_STORAGE location (thumbor_result_storage/resized_images). It appears that the newer version of Thumbor we're using has changed its functionality as follows:

When Thumbor receives a resize request, it first checks if it already has a resized version of that image in its RESULT_STORAGE folder. If it does, it simply returns it with no further action taken. If it does not already have the resized version, it checks to see if it has the non-resized version stored in FILE_STORAGE. If it does, it resizes the locally downloaded version, stores it to RESULT_STORAGE, and returns it to the client. Finally, if it has neither the resized version in RESULT_STORAGE nor the original version in FILE_STORAGE, it will download the original version from the URL provided, store it to FILE_STORAGE, and continue from there.

All along the way, Thumbor is trying to do as little work as possible before returning the resized version to the client in the interest of minimizing response time. What this means for us is that when an image gets changed, in order to get all the resized versions on the website to update, we have to both delete the old "original" image from FILE_STORAGE, as well as all resized variants in RESULT_STORAGE. Currently the Tinker code only removes the "original" from FILE_STORAGE, so that's why I'm making this issue.

To remove the resized variants, I think it would be most efficient to make use of Bash scripting commands, similar to how the cache-clear module already calls the `rm` command on the "original" image. I think the best way to do the resized variant deletion would be to use this command:

`find /opt/thumbor/resized_images -type f -path "*news/articles/2018/images/laurel-bunker.jpg" | xargs rm`

but maybe use some variable formatting...
```
from subprocess import call

THUMBOR_RESULT_STORAGE = '/opt/thumbor/resized_images

def delete_resized_images(path):
    # Sanitize path to not have any leading '/'
    sanitized_path = path  # TODO

    bash_command = 'find %s -type f -path "*%s" | xargs rm' % (app.config('THUMBOR_RESULT_STORAGE'), sanitized_path)
    call(bash_command, shell=True)  # This is advised against by some SO articles, so maybe find an alternate way to pipe find's output into xargs rm?
```

I'm hopeful that this will let this new cache-clear module clear both the un-resized image, as well as all of its resized images, which will force Thumbor to fetch the updated image, and make the new resizes as necessary.

**Comment by c-schwarze** [comment]
Something like this might help: https://stackoverflow.com/questions/1548704/delete-multiple-files-matching-a-pattern

**Comment by phg49389** [comment]
Something that could be done even further: 

- Check if the image being cleared from Thumbor is a www.bethel.edu image
- If it is, use Varnish's Refresh/Purge API to purge the image from Varnish first, and then refresh the cdn.bethel.edu/resize URL to get all 4 cache destinations restored "simultaneously" (technically sequential, but only one click for the users)

**Comment by c-schwarze** [comment]
@josiahtillman this is done, correct?

**Comment by josiahtillman** [comment]
Yup, this is done
